### ISSUE TITLE
تمام منابع و معرفی‌های انجام شده در وبسایت منابع فارسی بیتکوین به سیمرغ اضافه شود

### ISSUE THREAD

**Issue by mbaniasad** [simorgh-me/simorgh.me#4]
- طراحی پیج‌ها
- طراحی ادرس های استاتیک مناسب
- بحث در باره‌ی دستی بندی‌ها
- سیستم برای بروزرسانی و سینک کردن

**Comment by ghost** [comment]
الان این پیشنهاده یه ایده هست یا درخواست انجام پروژه. اون سایت هست(بیتکویندی) چرا باید اینجا هم تغییر کنه؟ چون تو جمع آوری کامیونیتی موفق نبوده؟ دلیل نداره گروه سیمرغ که بر اساس ارزش گذاری‌ها و باور‌های عدم تمرکز شکل گرفته درگیر این موضوع بشه. اگر نیاز هست تو گروه تلگرامی سیمرغ(گروه اصلی) به بحث گذاشته بشه
